### ISSUE TITLE
cnes plugin does not support Sonarqube Community Edition V7.7

### ISSUE THREAD

**Issue by zhankangbao** [lequal/sonar-cnes-report#64]
### Expected behavior
Detected SonarQube version: 7.7.0
[ERROR] Unknown URL error sent by SonarQube server (code 404), please check cnesreport compatibility with your SonarQube server version.
### Steps to reproduce behavior
cnesreport 2.1.0
SonarQube version: 7.7.0
### Detection version
cnesreport 2.1.0
SonarQube version: 7.7.0

**Comment by Sancretor** [comment]
Hi @zhankangbao !  

Thank you for your feedback, it's appreciated.  
Unfortunately, the Sonar CNES Report is not compatible by design with SonarQube 7.7.  
This is showed in the project's README here : https://github.com/lequal/sonar-cnes-report#compatibility-matrix  
  
We don't have any planned task on such compatibility upgrade now, but feel free to contribute to this project, Pull Requests are welcomed !
