### ISSUE TITLE
Installation unclear

### ISSUE THREAD

**Issue by Captain67777** [lequal/sonar-cnes-report#95]
I downloaded the file as sonar-cnes-report-master.zip and renamed it to cnesreport.jar.
I have an instance of SonarQube (version 7.9) running.

I stopped this instance and put cnesreport.jar into directory extensions\plugins. Then i restarted  SonarQube but it won't start anymore because of added .jar.

So I gave up on running cnes as a plugin and removed the .jar from the plugin directory and restarted SonarQube succesfully.

Then I tried to run the jar standalone so (from directory containing the jar) I enter command java -jar cnesreport.jar -p <myprojectId> but then i get error 'Error: Invalid or corrupt jarfile cnesreport.jar'.

Now i am stuck..

Anyone who can help me out?

**Comment by Sancretor** [comment]
Hi @Captain67777 !
Thanks for your feedback, we appreciate it !

If I understand you correctly, the issue comes from the way you install the plugin.
The ".zip" file you downloaded contains the source code from the master branch, so it is not package as a SonarQube plugin, and rename it as a ".jar" file won't do the trick.
With every release, we provide this specific JAR package.

See the Release page to download the JAR file that matches the needed version : https://github.com/lequal/sonar-cnes-report/releases

Let us know if you manage to solve your issue.

**Comment by Captain67777** [comment]
Thx for your quick reply.
I clearly missed the 'Releases' tab / link...
Using the .jar i succeeded in creating a report, both using standalone and plugin mode.
Problem solved :-)
