### ISSUE TITLE
get report only from master branch analysis ?

### ISSUE THREAD

**Issue by nykykof** [lequal/sonar-cnes-report#96]
### Expected behavior
Should allow to generate report from an analysis on a non-master branch. it would be nice if we could pass the branch from which we want to generate report (when multibranches plugin is enable on sonarQube)
### Actual behavior
we can generate report only from analysis on master branch
### Steps to reproduce behavior
* enable multibranches plugin on sonar
* make an analysis on develop
* try to generate report from the prvious analysis
### Detection version
latest

**Comment by Sancretor** [comment]
Hi @nykykof !

Thanks for your feedback, we appreciate it !  
This would be a useful feature for the project.  
Unfortunately, we don't have yet a Developer Edition of SonarQube in order to work on the branch plugin.  
I can't tell when we'll be able to look into it, but in the meantime feel free to send us a PR !

**Comment by mperelmu** [comment]
As far as i know, sonarqube branch plugin is now available for community edition 
https://github.com/mc1arke/sonarqube-community-branch-plugin

**Comment by begarco** [comment]
Hi @mperelmu 

The cnesreport plugin is based on public stable SonarQube feature. Relying on a community plugin feature is not yet forseen but it could be discussed.

**Comment by DatzAtWork** [comment]
The branch-plugin aims to simulate the behaviour of the Developer Edition. I guess it can be used for developing and testing.
